services:
  # Frontend Static Site
  - type: web
    name: flask-app-frontend-dev
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable

  # Backend API (if deployed separately on Render)
  - type: web
    name: flask-app-backend-dev
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt && python run_migrations.py
    startCommand: cd backend && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

