"""Add role column and reorganize ssn

Revision ID: 04161cd1902f
Revises: 
Create Date: 2025-10-29 19:50:56.022426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04161cd1902f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
