"""Add middle_name column to candidate table

Revision ID: 70628d167eda
Revises: e8f5a6b7c8d9
Create Date: 2025-10-26 15:51:46.926890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70628d167eda'
down_revision = 'e8f5a6b7c8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
