"""Add SSN column to candidate table

Revision ID: 85fc35d7805b
Revises: d02350509366
Create Date: 2025-10-26 23:31:11.107844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fc35d7805b'
down_revision = 'd02350509366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssn', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_candidate_ssn'), ['ssn'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_ssn'))
        batch_op.drop_column('ssn')

    # ### end Alembic commands ###
