"""Add resume_content column

Revision ID: a5daeee442bd
Revises: d49adb647396
Create Date: 2025-10-21 23:53:19.235004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5daeee442bd'
down_revision = 'd49adb647396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_job_note')
    with op.batch_alter_table('candidate_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('docx_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_job', schema=None) as batch_op:
        batch_op.drop_column('docx_path')
        batch_op.drop_column('resume_content')

    op.create_table('candidate_job_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
