"""removed the tested

Revision ID: d02350509366
Revises: 70628d167eda
Create Date: 2025-10-26 16:11:36.862170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02350509366'
down_revision = '70628d167eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
