"""init

Revision ID: d49adb647396
Revises: 
Create Date: 2025-10-10 23:24:28.011604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49adb647396'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_wage', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('contact_current_employer', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('recent_degree', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('authorized_work_us', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('authorized_without_sponsorship', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('referral_source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('at_least_18', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('needs_visa_sponsorship', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('family_in_org', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certificates', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('certificates')
        batch_op.drop_column('education')
        batch_op.drop_column('availability')
        batch_op.drop_column('family_in_org')
        batch_op.drop_column('needs_visa_sponsorship')
        batch_op.drop_column('at_least_18')
        batch_op.drop_column('referral_source')
        batch_op.drop_column('authorized_without_sponsorship')
        batch_op.drop_column('authorized_work_us')
        batch_op.drop_column('recent_degree')
        batch_op.drop_column('contact_current_employer')
        batch_op.drop_column('expected_wage')

    # ### end Alembic commands ###
