"""add_subscription_type_column

Revision ID: df629fdccf7e
Revises: b7e3f4c5d6a7
Create Date: 2025-10-25 11:45:38.896976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df629fdccf7e'
down_revision = 'b7e3f4c5d6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('subscription_type')

    # ### end Alembic commands ###
